# Generated by Django 4.1 on 2022-08-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Funny Stories', 'Funny Stories'), ('Students Colorful Lives', 'Students Colorful Lives'), ('Daily', 'Daily'), ('Language Tips', 'Language Tips')], default='Funny Stories', max_length=255),
        ),
    ]
