# Generated by Django 4.1 on 2022-09-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_tag_blog_tag_alter_blog_content_alter_blog_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tag',
            field=models.CharField(blank=True, choices=[('Comprehensible Input', 'Comprehensible Input')], default='humor', max_length=255),
        ),
    ]
