# Generated by Django 4.1 on 2022-09-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_blog_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Funny Stories', 'Funny Stories'), ('Students Colorful Lives', 'Students Colorful Lives'), ('Daily', 'Daily'), ('Language Tips', 'Language Tips'), ('Resources', 'Resources'), ('Growth', 'Growth')], default='Funny Stories', max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tag',
            field=models.CharField(choices=[('Comprehensible Input', 'Comprehensible Input'), ('Humor', 'Humor'), ('Life-style', 'Life-style'), ('Sharing', 'Sharing'), ('Encouraging', 'Encouraging'), ('Little Secret', 'Little Secret')], default='humor', max_length=255),
        ),
    ]
