# Generated by Django 4.1.1 on 2022-10-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_blog_category_alter_blog_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tag',
            field=models.CharField(choices=[('Comprehensible Input', 'Comprehensible Input'), ('Humor', 'Humor'), ('Life-style', 'Life-style'), ('Feelings', 'Feelings'), ('Encouraging', 'Encouraging'), ('Little Secret', 'Little Secret')], default='humor', max_length=255),
        ),
    ]
